### ISSUE TITLE
C# Sdk

### ISSUE THREAD

**Issue by rolfwessels** [Mastercard/sdk-core-csharp#1]
I wanted to try out the MasterCard Merchant info API and came across the SDK. I have some advice to make the SDK a bit more usable for C# developers. 
- C# is a typed language. Models should preferably be defined in the SDK and used as strongly typed objects. This is easy to do with Json.net which you are already using. For example  `var m = JsonConvert.DeserializeObject<MerchantIdentifierResponse>(json);` would deserialize json into strongly typed object called `MerchantIdentifierResponse` . This makes the SDK infinitely more usable since each object is now fully defined and can be used as  `m.MerchantIds.Message` (works great with intellisense)
- C# also allows dynamic objects. This can be useful if you believe that your responses will change regularly (otherwise stick to typed models). Json.net provides this functionality, eg. `dynamic m = JsonConvert.DeserializeObject("{ 'MerchantIds': { 'Message': 'c# can be dynamic'}}");` will deserialize the JSON into an dynamic object that can be used like a normal object eg. `string message =  m.MerchantIds.Message;`
- I personally prefer strongly typed models but the dynamic objects are a lot better and easier to implement than the current `dictionary<string,object>` design. Dynamic would also have solved the issue where seemingly any call other than the "microsoft" example is failing with the exception "The given key was not present in the dictionary.".
  
  ```
  RequestMap map = new RequestMap();
  map.Set("Type", "FuzzyMatch");
  map.Set("MerchantId","Uber Technologies Ltd");
  MerchantIdentifier response = MerchantIdentifier.Query(map); // < throws exception because the object is {error ....} 
  ```
- Prefer non static objects and interfaces over static class. Static objects are great but they can become an anti-pattern very quickly if used without consideration. Here are a few reasons why, 1. Static objects are hard to unit test , 2. They don't work well with IOC, 3. In this code it causes temporal coupling.
- C# has a naming convention https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx. `ApiConfig.setAuthentication(` does not follow this convention. Conforming to this convention makes it easier for developers to understand the SDK and maybe in future even contribute to the SDK.
- As a general rule you would add a separate project containing tests. Tests are separate to your normal code and you don't want it packaged with your source code into the same DLL.
- Lastly, I guess this was a mistake but I assume you don't want to commit your P12 prod key with the source code.  

I hope this makes sense. When I look at the SDK, it seems that like someone tried to convert JS code directly into C# code. This is not easy to do because the JS paradigm is so vastly different to the C# paradigm.

**Comment by ade90036** [comment]
Hi Rolf,

Thanks for your feedback,

Did i mentioned that we have a new developer portal, which embodies our new
philosophy in the API space.

Given the fact that todays average developer is a polyglot, meaning that
he/she could choose a multitude of languages and frameworks at his
disposal; the ability to produce an SDK which is concise, intuitive, easy
to use with little to none boilerplate code across languages was our
principal goal.

The problem, which we do understand in its entirety, of a "strongly typed"
paradigm is that each type of request and variations requires careful model
representation. Also it didn't help the fact that we are dealing with
legacy services and therefore we have no way to hide some of this
complexity away by redesign and refactoring.

Take for example this JSON object:
{
   "AccountInquiry":{
      "AccountNumber":"5343434343434343",
      "Verification":{
         "ICU":"Default"
      }
   }
}

If we had created models for represent the request we would have ended up
with this as the instantiation:
AccountInquiry accountInquiry = new AccountInquiry();
Verification verification = new Verification();
verification.SetICU("Default");
accountInquiry.SetAccount("5343434343434343");
accountInquiry.SetVerification(verification)

while you only require:
var request = new RequestMap().Set("AccountInquiry.AccountNumber",
"5343434343434343").Set("AccountInquiry.Verification.ICU", "Default");

I know that compilation process may give you some certainties that the code
is compiled and thus that there are no errors in sight, but this is never
true when you are dealing with remote services where business rules are
evaluated at runtime in the servers. Hence, some of out complex request
validation (including field validation) are also performed at runtime in
our servers.


So what i'm taking away from your feedback:

   - exploration of dynamic objects
   - exclude tests from artifact generation
   - fix naming convention

The other points are a bit of a diminuendo, so i won't get into.

In the mean time if you wish to fork our project to showcase how some of
these dynamic objects are done, you are more than welcome.

Also you mentioned IOC, can you give us the name of the IOC framework that
you are using so we can try to test it out?

Regards

Andrea

**Comment by rolfwessels** [comment]
Hi Andrea,

Thanks for the feedback. Just as a quick feedback, lately I use Autofac for most of my projects as an IOC container.

I'm looking at your sample, that looks very much like the way you would do it in Java. However in C# we don't really use getters and setters. We have properties (https://msdn.microsoft.com/en-za/library/x9fsa0sw.aspx). In C# you would initiate the object as you described as follows (this can be done in one line but for readability I wont do that) .  

var  accountInquiry =  new AccountInquiry {
      AccountNumber = "5343434343434343",
      Verification = new Verification {
         Icu = "Default"
      }
   };

As you can see it is very similar to the way you would in JS/JSON.

Ultimately, I think that you can agree that if I said that in Javascript you should do the following:

let request = RequestMap().set("AccountInquiry.AccountNumber",
"5343434343434343").set("AccountInquiry.Verification.ICU", "Default");

Instead of :

let request = {
   AccountInquiry:{
      AccountNumber:"5343434343434343",
       Verification:{
         ICU:"Default"
      }
   }};

I'm sure you would think that I am being rather silly or at least very inefficient. 

In the end I can try to argue the merit of SDK being tailored to the language but I believe that it might be diminuendo, as you have already politely pointed out. 

If you/MasterCard really want to provide a SDK that's tailored around the language making it intuitive and easy to use in that language, then I would be willing to help out, otherwise I'm perfectly happy to agree to disagree :-)

Regards

Rolf

**Comment by ade90036** [comment]
Hi Rolf

Certainty will try the IOC container.

You are right in your observation. We are primarily a Java house and .net
is not our forte. (Should really quit using these musical terminologies).
We have based our C# SDKs from our Java SDK, hence a lot of concepts and
design have been borrowed from that.

I have personally have experience with .net technology (based on 3.0 and
3.5) and certainly some of the feature that you have mentioned are very new
to me.  So there is definitely a knowledge gap and certainly when i
mentioned that the other points were a "diminuendo" (balls, i've done
again!!); i simply meant that they didn't resonate with me as immediate
concern.

However your point that you are making is very right.

For reason which goes behond the scope of this email and which concerns
complex systems within MasterCard, we have not done a good job in the past
to keep our SDKs updated, so the model which is represented in the SDK is
what is expected from the underline service. This has been issue for
numerous customers and the ability to produce a new SDKs upon such change
has been known as a slow forthcoming.

So we have decided to part from a strongly typed objects in-favor of a more
loosely coupled approach. While still maintaining request validation and
business rule validation on the server.

MasterCard has invested a lot of resource in making out SDKs easier and
intuitive and to appeal to a larger audience and certainly your feedback is
most valuable.

So, keeping this in mind, if you would like to create a branch and maybe
showcase on some of your designs on how to instantiate an object (without
being a strongly typed) while maintaining best practices for C#,  we would
be certainly be most interested.

Take a look at the tests we a have done to hit our sandbox environment,
those could be a good starting point for you.


   -
   https://github.com/MasterCard/sdk-core-csharp/blob/master/Test/Functional/AudiencesSegmentTest.cs
   -
   https://github.com/MasterCard/sdk-core-csharp/blob/master/Test/Functional/ParametersTest.cs
   -
   https://github.com/MasterCard/sdk-core-csharp/blob/master/Test/Functional/InsightsTest.cs

Regards

Andrea

**Comment by rolfwessels** [comment]
Sorry, It's been a crazy week. I will try to find some time to draw up some samples, preferably using those tests.

**Comment by rolfwessels** [comment]
Ok, I have created a sample. It uses c# dynamic. Obviously it is just a sample and I have not spent too much time around defensive coding.

``` 
dynamic request = new { CurrentRow = 1, Offset = 25 };
// action
var response = Parameters.QueryDynamic(request);
// assert
Assert.That("NO", Is.EqualTo((string)response.ParameterList.ParameterArray.Parameter[1].Ecomm).IgnoreCase);
```
It uses the existing code to build the URL and the Authentication, it then uses Restsharp for the for requesting and then JSON.net for the parsing. 

On a side note , restsharp would generally be the only thing that you would since it already contains a builtin json/xml parser. So if you want to make your footprint a bit smaller (and you go with the dynamic only implementation) you can really forgo the restsharp bit. I say this because you are really just using it as a glorified WebRequest (https://msdn.microsoft.com/en-us/library/456dfw4f(v=vs.110).aspx) and not as a full end to end rest framework (which it is awesome at when responses are statically typed). 

So again (sorry for hammering on about this), I don't think that C# is good (compared to JS or Python) at being dynamic. It can do it but it is not a first class citizen to the language. Doing an SDK like this as a dynamic c# implementation will require the implementer to have a deeper understanding of the underlying API than he/she would generally need if it was a static implementation.

Anyway, there is your dynamic sample. Happy to hear your thoughts.

**Comment by rolfwessels** [comment]
Just realised that I did not add the branch information. https://github.com/rolfwessels/sdk-core-csharp/commits/feature-sample-of-dynamic-objects

**Comment by ade90036** [comment]
Hi Rolf. I'm on annual leave. I'll look at the branch when I'm back. Thanks.

**Comment by ade90036** [comment]
Hi Rolf, 

Apologies for not getting back to you earlier, i was not on a Holliday until now!  😄 

i've reviewed the code and i really like the way the dynamic object replaces the instance object representing the response. 

So since the dynamic object replaces the response object it will have to replace the request too.

I would like to understand how the code will change for the request generation, so i can start thinking in a way to update our code generator from swagger.  

At the moment we spit out the JSON for NodeJS SDKs  so the request is simply  becomes: 
```javascript
var requestData = {
  "quoterequest": {
    "quote_reference": "07120438764796105811",
    "sender_account_uri": "tel:+2130000",
    "recipient_account_uri": "tel:+254060005",
    "remittance_amount": {
      "amount": "100.00",
      "currency": "USD"
    },
    "quote_type": {
      "forward": {
        "fees_included": "true"
      }
    },
    "originating_country": "USA",
    "additional_data": {
      "data_field": [
        {
          "name": "111",
          "value": "Oak Street"
        },
        {
          "name": "112",
          "value": "any city"
        }
      ]
    }
  }
};
```

This is the same request but using our implementation (smartmaps)
```c#
            RequestMap map = new RequestMap();
            map.Set ("quoterequest.quote_reference", "07129451431668592931");
            map.Set ("quoterequest.sender_account_uri", "tel:+2130000");
            map.Set ("quoterequest.recipient_account_uri", "tel:+254060005");
            map.Set ("quoterequest.remittance_amount.amount", "100.00");
            map.Set ("quoterequest.remittance_amount.currency", "USD");
            map.Set ("quoterequest.quote_type.forward.fees_included", "true");
            map.Set ("quoterequest.originating_country", "USA");
            map.Set ("quoterequest.additional_data.data_field[0].name", "111");
            map.Set ("quoterequest.additional_data.data_field[0].value", "Oak Street");
            map.Set ("quoterequest.additional_data.data_field[1].name", "112");
            map.Set ("quoterequest.additional_data.data_field[1].value", "any city");
```

How would i capture this request in C# using dynamic / ExpandoObject? (keep in mind we are also capturing a list?).

Also are dynamic object also part of the language and therefore present in the .NET Core? 

Your feedback is very appreciated.

Regards

**Comment by rolfwessels** [comment]
Hi,

Firstly, if your API is documented using Swagger then you could look at a tool that generates the API/SDK bits that you need automagically, I was looking at https://github.com/NSwag/NSwag, just from the screen shots it seems like the tool that might solve your reluctance to build static models.

As for the dynamic part of the request, you can take that sample that I wrote as an example.
```
dynamic request = new {CurrentRow = 1, Offset = 25};
var response = Parameters.QueryDynamic(request);
```

The request there is dynamic, In this case we are using it as parameters, if you wanted json from it. You can just pass that to the json serialiser.

So from your example it would be:
```
var requestData =new {
		quoterequest = new
		{
			quote_reference = "07120438764796105811",
			sender_account_uri = "tel:+2130000",
			recipient_account_uri = "tel:+254060005",
			remittance_amount = new
			{
				amount = "100.00",
				currency = "USD"
			},
			quote_type = new
			{
				forward = new
				{
					fees_included = "true"
				}
			},
			originating_country = "USA",
			additional_data = new
			{
				data_field = new[] {
			  new
			  {
				  name = "111",
				  value = "Oak Street"
			  },
			  new
			  {
				  name = "112",
				  value = "any city"
			  }
			}
			}
		}
	};
JsonConverter.Serialize(requestData ); 

```

Will build a dynamic object with arrays and everything (expando objects are only needed if you are planing to move the objects around across projects. For now you probably don't need it).

Regards

**Comment by ofuochi** [comment]
I always get the error "Failed to process request", with the reason being "SYSTEM_ERROR". It's really as my organisation is trying to integrate the MoneySend API to our system. 
I've set all the parameters correct but still get this error. I even used the updated MasterCard Core package to set the http proxy as suggested [here](https://developer.mastercard.com/page/csharp-sdk-guide#http-proxy). When I set the proxy however, I get the error "Cannot connect to remote server" and the most annoying part in the documentation is giving a [support area ](https://mastercarddevelopersupport.desk.com/) link that doesn't exist.
I'm really frustrated right now as I can complete my job until I find my way around this but I can't seem to get any help and that's why I came here. Hopefully, I'll get some help. Thank you in advance

**Comment by ade90036** [comment]
Could you enable ApiConfig.SetDebug(true) and report the full error (wire
logging) that yoy are seeing.

Please anonymise any personal information please.

I will enquire about the broken link.

Thanks.

**Comment by ofuochi** [comment]
Hello @ade90036 find below a screenshot of the error I get when I set proxy 
![image](https://user-images.githubusercontent.com/13614165/29449514-f8291898-83f2-11e7-9b91-8f20cb11f45b.png)

And below is the error I get without setting proxy
![image](https://user-images.githubusercontent.com/13614165/29451083-3b0b1a5c-83f9-11e7-88ec-f40748d9fb74.png)

**Comment by ade90036** [comment]
@ofuochi , i can't debug the issue by looking at a screenshot of your debugger. 

If you are getting an error before enabling http-proxy, how you expect do you expect it work?

Could you use the following command in the SDK initialisation section,
```CSharp
ApiConsole.SetDebug(true)
```
and report back with the wire logging which is generated in the console.

It should be something like this:
```
1142 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - >>Execute(action='query', resourcePaht='/atms/v1/country', requestMap='MasterCard.Api.Locations.ATMCountries'
1203 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - excute(), request.Method='GET'
1203 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - excute(), request.URL=https://sandbox.api.mastercard.com/atms/v1/country?Format=JSON
1204 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - excute(), request.Header=
1204 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - {Accept=application/json, Content-Type=application/json, User-Agent=CSharp-SDK/1.0.4, Authorization=OAuth oauth_consumer_key="L5BsiPgaF-O3qA36znUATgQXwJB6MRoMSdhjd7wt50c97279%2150596e52466e3966546d434b7354584c4975693238513d3d",oauth_nonce="AVozvmE1kmOSJuVNk",oauth_signature="L2w1EIIEz2AHhQ%2Bg4Fn7Iw%2FjG6gtv87eVrCovGY4ZNJE08a1YuzS0t3GuvGW5I9RvGJ9LlZFA9ju56zqrLlef0rFGWnuBi4I2gSdtr4CG926nOKhKOc6udu3nL8pdnxa9TAnJSWCLELbt%2B6YcxPLQbDhZkjlKiQWKpxDppzx0el2C4C30rZgapw4aUesElUaxPRn7Xvf4Z9rsCxCtRp0v6jSEZNSHZKcmd885YndPMqYkhBaUX7pqj1aPEi7a8%2FB7ABxINHjJNIgD8tqKjrT7Jx30J2ReDWxxtdeNqssKz32uUbQ5Fv9aKZhnTd2jTKNBOy5RNWEcGBuL0xKeTs8hg%3D%3D",oauth_signature_method="RSA-SHA256",oauth_timestamp="1488876870",oauth_version="1.0"}
1207 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - excute(), request.Body=
1207 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - {}
4990 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - Execute(), response.Header=
4990 [Worker#STA_NP] DEBUG MasterCard.Core.ApiController (null) - {Pragma=No-cache, Keep-Alive=timeout=15, max=100, Connection=Keep-Alive, Content-Length=11086, Cache-Control=no-cache, Content-Type=application/json, Date=Tue, 07 Mar 2017 08:53:58 GMT, Expires=Wed, 31 Dec 1969 18:00:00 CST, Set-Cookie=APIGW_51_cluster_JSESSIONID=rBD7GaLj8usXxLLy+puqsg__; Path=/mosp; Secure,TS01b346c2=01772feb4b92ab6a6ffa6499e5dca061bf9d0fc92c13ab169ecb0c93990d59d1089ec836cd; Path=/; HTTPOnly,TS01eb8160=01772feb4bb61740b3a6a914c4f9d506d851500572ec75001788e060d80181914789608004f5e39f0353d23e69516f779f2f967efe; path=/mosp; HTTPonly, X-Powered-By=DevTest/9.1.0 (9.1.0.399); CA, Inc.}
```

All of it please.. 

Regards

**Comment by ade90036** [comment]
@ofuochi, this is not the same issue as above, so i would ask you to create a open a new ticket, please..

**Comment by ade90036** [comment]
leaving it open untill you create a new ticket and then i'm closing this.. 😄

**Comment by ade90036** [comment]
ooo

**Comment by kenny-chow-my** [comment]
since this issue is 2 years old, I will be closing this topic. If you wish to continue discussion, please feel free to reopen.
