### ISSUE TITLE
Bug in MasterCard.Core.Model.BaseObject.Execute<T>(string operationUUID, T inputObject)

### ISSUE THREAD

**Issue by pristinesource** [Mastercard/sdk-core-csharp#4]
https://github.com/Mastercard/sdk-core-csharp/blob/master/Sources/MasterCard/Core/Model/BaseObject.cs#L81

You check to see if response is null and if it is not, you use it, but in the else statement, it looks like you use it anyway (possibly creating a null reference exception).

I think what was supposed to happen here is more like this, where it checks if the inputObject is null instead:
    https://gist.github.com/pristinesource/b54458006285986d9657f2ba359f7c00#file-baseobject-cs-L81
(Lines 81-91)

**Comment by pristinesource** [comment]
Also, a better way to create a new instance of T in your method  is to add the "new()" type constraint and create the instance directly.  "Activator.CreateInstance" uses reflection (bad!), whereas this way does not.

Here is an example of what I mean:
https://gist.github.com/pristinesource/730b35389d4daa1bce3bba9adba28692
(Lines 61, 76 and 89)

**Comment by ade90036** [comment]
Hi there, 

thanks for reporting the issue. 
I agree that if the reponse is null then you could have an issue. 

I'm not sure what you have shown me in your file is going to work, you are never populating the dictionary with the response, so it will always return an empty dictionary. 
``` csharp
Dictionary<String,Object> response = apiController.Execute(inputObject.GetOperationConfig(operationUUID), inputObject.GetOperationMetadata(), inputObject);

//arizzini: see here..
dictionary = dictionary ?? new Dictionary<string, object>();
if (inputObject != null)
{
	inputObject.Clear();
	inputObject.AddAll(dictionary);
}
else
{
	inputObject = (T) Activator.CreateInstance (inputObject.GetType ());
	inputObject.AddAll(dictionary);
}
return inputObject;
```
The next issue, i'm not sure it is really an issue and i don't agree with your statement: "Use of reflection is bad". There are a lot of technologies which are based on reflection such as IOC containers, NHibernate and others. 

I do agree that what what you have suggested is a better syntax.

If you create a pull request this the changes in questions, i'm going to accept it.
Make sure to do some testing.

Regards

**Comment by pristinesource** [comment]
Lol, the statement about "using reflection is bad" was a joke. There are always good uses for using reflection (that is why it exists), and I certainly use it when needed.  It's just that sometimes there is a non-reflection way to do things that would provide less overhead than reflection (but may not be as obvious of a solution as reflection). We sometimes use the "reflection is bad" statement as an internal joke here at my company when such a situation occurs, I meant no offense. 

As for the dictionary, I have the wrong variable name, it should be like this:

```csharp
IDictionary<String,Object> response = apiController.Execute (inputObject.GetOperationConfig(operationUUID), inputObject.GetOperationMetadata(), inputObject);
response = response ?? new Dictionary<String, Object>();
if (inputObject != null)
{
	inputObject.Clear();
	inputObject.AddAll(response);
}
else
{
	inputObject = new T();
	inputObject.AddAll(response);
}
```


I will have that corrected in the pull request.

And I will do some testing ;)

Thank you for this awesome SDK!!!!!!!

**Comment by pristinesource** [comment]
I created a pull request for this:

https://github.com/Mastercard/sdk-core-csharp/pull/6

**Comment by ade90036** [comment]
You are very welcomed 😊

**Comment by ade90036** [comment]
merged!, closing
