### ISSUE TITLE
Need to be able to specify X509Certificate2 flags because of Azure

### ISSUE THREAD

**Issue by pristinesource** [Mastercard/sdk-core-csharp#5]
When using this library on Azure we need to be able to specify the X509Certificate2 flags.
Azure Wep Apps need to specify the "MachineKeySet" flag: http://blog.tylerdoerksen.ca/2015/11/29/pfx-certificate-files-and-azure-web-apps/

Here is an example of what I think it should look like:
https://gist.github.com/pristinesource/0a2aeebad6a97e55c26aecc1b583f0c7
(Lines 57-59)

Also, in that same Gist, I added a second constructor to allow loading the key info from a byte array instead of a file (Lines 66-73). This is very useful when running on a cloud environment and the key may be stored in a key manager such as Azure's KeyVault and not a file.

**Comment by pristinesource** [comment]
Also, your FieldLevelEncryption class (MasterCard.Core.Security.Fle in v1.4.2) could benefit from these same improvements to allow setting X509Certificate2 flags and being able to pass in the X509Certificate2 key data via a byte array to an alternate constructor.

**Comment by ade90036** [comment]
I agree, can you create a pull request with the new additional constructors. I will accept the changes and publish a new version..  

Thanks

**Comment by pristinesource** [comment]
I will certainly create a pull request for the new constructors, but I will not be able to do it for your FieldLevelEncryption class (MasterCard.Core.Security.Fle in v1.4.2) and your InstallmentCryptogaphy class (MasterCard.Core.Security.Installments in v1.4.2) because the code base here is still at v1.4.0 which does not include those classes.

https://github.com/Mastercard/sdk-core-csharp/tree/master/Sources/MasterCard/Core/Security

Do you want me to wait until you have pushed to GitHub before I make my pull request for this so I can create the constructors for all of the classes that need it?

**Comment by ade90036** [comment]
Yes.. i nerd to synch out interna repo with github. First think tomorrow
morning. Thanks again.

**Comment by ade90036** [comment]
*need*

**Comment by ade90036** [comment]
i've updated the sources with the latest code.. if you want to create the other pull request for the other constructors i will gladly merge it in. 

Regards

Andrea

**Comment by pristinesource** [comment]
created pull request at: https://github.com/Mastercard/sdk-core-csharp/pull/7

**Comment by ade90036** [comment]
merged.. closing..
