### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by ofuochi** [Mastercard/sdk-core-csharp#8]
@ade90036 See the response I get below.
[SocketException (0x274d): No connection could be made because the target machine actively refused it 127.0.0.1:8181]
   System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) +185
   System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception) +506

[WebException: Unable to connect to the remote server]
   System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context) +916
   System.Net.HttpWebRequest.GetRequestStream() +13
   RestSharp.Http.WriteRequestBody(HttpWebRequest webRequest) +91
   RestSharp.Http.PostPutInternal(String method) +39
   RestSharp.Http.AsPost(String httpMethod) +30
   RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method) +8
   RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse) +105

[ApiException: Unable to connect to the remote server]
   MasterCard.Core.ApiController.Execute(OperationConfig config, OperationMetadata metadata, BaseObject requestMap) +1126
   MasterCard.Core.Model.BaseObject.Execute(String operationUUID, T inputObject) +140

**Comment by ade90036** [comment]
What proxy are you using?

 It seems the your proxy server is refusing the connection. 

Could you give me more details on what proxy server you are using?

Thabks

**Comment by ofuochi** [comment]
Proxy: 10.0.0.127
Port: 80

**Comment by ade90036** [comment]
In your code you have specified this proxy setting.

The exceptions seems to specify
host: 127.0.0.1
Port: 8181

Could you please check your setup?

**Comment by ade90036** [comment]
Could you share you SDK initialisation code please?

**Comment by ofuochi** [comment]
the installation code: ````Install-Package MasterCard-MoneySend````
I used that proxy setting as instructed in the documentation however when I used my proxy, it throws the error ````The remote server returned an error: (407) Proxy Authentication Required.````

**Comment by ade90036** [comment]
Sorry, what i mean with initialisation code, it is the setup of the SDK: 

```
ApiConfig.SetEnvironment(Environment.SANDBOX);
ApiConfig.Proxy(bla);
```

That is an proxy authentication error.
You proxy is password protected and the SDK is failing to connect.

During your SDK setup (which should only happen once), you need to setup the proxy like this:

```
WebProxy proxy = WebProxy("127.0.0.1", 8181);
ApiConfig.SetProxy(proxy);
```
WebProxy contains a constructor which allows to specify credentials for the proxy. (Please check MDSN documentation)
https://msdn.microsoft.com/en-us/library/system.net.webproxy(v=vs.110).aspx

Regards

**Comment by ofuochi** [comment]
Here is my initialization code:
````
 const string consumerKey = "UTfbhDCSeNYvJpLL5l028sWL9it739PYh6LU5lZja15xcRpY!fd209e6c579dc9d7be52da93d35ae6b6c167c174690b72fa";   // You should copy this from "My Keys" on your project page e.g. UTfbhDCSeNYvJpLL5l028sWL9it739PYh6LU5lZja15xcRpY!fd209e6c579dc9d7be52da93d35ae6b6c167c174690b72fa
            const string keyAlias = "keyalias";   // For production: change this to the key alias you chose when you created your production key
            const string keyPassword = "keystorepassword";   // For production: change this to the key alias you chose when you created your production key
            var path = Util.GetCurrenyAssemblyPath(); // This returns the path to your assembly so it be used to locate your cert
            var certPath = System.IO.Path.Combine(path, "MoneySend-1502869853-sandbox.p12"); // e.g. /Users/yourname/project/sandbox.p12 | C:\Users\yourname\project\sandbox.p12
            ApiConfig.SetAuthentication(new OAuthAuthentication(consumerKey, certPath, keyAlias, keyPassword));   // You only need to set this once
            ApiConfig.SetDebug(true);   // Enable http wire logging
            ApiConfig.SetSandbox(true);

            var proxy = new WebProxy("127.0.0.1", 8181);
            ApiConfig.SetProxy(proxy);
````

**Comment by ade90036** [comment]
Ok, as i was mentioning in my previous post: 

```
//your proxy confiuguration goes here.
var proxy = new WebProxy("10.0.0.127", 80);
ApiConfig.SetProxy(proxy);
```

there is constructor which allows to create the WebProxy with credentials.

```
public WebProxy(
	Uri Address,
	bool BypassOnLocal,
	string[] BypassList,
	ICredentials Credentials
)
```

please check the MSDN documentation for further information:
https://msdn.microsoft.com/en-us/library/zxzs1whe(v=vs.110).aspx

regards

**Comment by ofuochi** [comment]
I get the exception ````Failed to process request```` after setting my credentials like so;
````
 var proxy = new WebProxy("10.0.0.127", 80)
            {
                Address = new Uri("http://10.0.0.127:80/"),
                BypassProxyOnLocal = true,
                BypassArrayList = { },
                Credentials = new NetworkCredential("username","password")
            };
            ApiConfig.SetProxy(proxy);
````

**Comment by ade90036** [comment]
Ok.

Could you show me the wire log from you app:

Same as before:

```
ApiCong.SetDebug(true)
```

And report back. ☺

Thanks

On 18 Aug 2017 17:09, "Fortune" <notifications@github.com> wrote:

I get the exception Failed to process request after setting my credentials
like so;

 var proxy = new WebProxy("10.0.0.127", 80)
            {
                Address = new Uri("http://10.0.0.127:80/"),
                BypassProxyOnLocal = true,
                BypassArrayList = { },
                Credentials = new NetworkCredential("username","password")
            };
            ApiConfig.SetProxy(proxy);

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Mastercard/sdk-core-csharp/issues/8#issuecomment-323395333>,
or mute the thread

**Comment by ofuochi** [comment]
Hello @ade90036 I've been able to fix this by using the following settings;

````
 var proxy = new WebProxy
            {
                UseDefaultCredentials = true,
                BypassProxyOnLocal = true,
                Address = new Uri("http://myProxy:myPort")
            };
            ApiConfig.SetProxy(proxy);
````

Thank you very much! Now I can continue with the integration. 😃
