### ISSUE TITLE
Is there an update for the SDK to support .Net Core 2.0  in the near future?

### ISSUE THREAD

**Issue by meeras147** [Mastercard/sdk-core-csharp#9]
Currently building an application using .Net Core 2.0 framework. The current SDK is incompatible with my app. Would like to know if .Net Core 2.0 support is on the roadmap.

**Comment by kenny-chow-my** [comment]
@meeras147 we are looking into this. There are a couple of outstanding technical issues. Once we resolve those issues, official support should be possible. However, I can't provide you with any specific date or timeline at the moment.

**Comment by kenny-chow-my** [comment]
@meeras147 We have recently release C# Core SDK v1.5.0 which supports .Net Core 2.0 framework. Good luck with your project!

**Comment by meeras147** [comment]
Thank you so much!
